/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: TampaJoey (https://sketchfab.com/TampaJoey)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/security-camera-with-animations-textures-631834aba23f43a482e4de7120d68d19
Title: Security Camera (with Animations & Textures)
*/

import React, { useRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"
import scene from "../assets/3d/cctv_camera2.glb"

export function CameraFoot(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="Camerafbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.015}
            position={[0, 0.4, 0.3]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_12"
                    geometry={nodes.Object_12.geometry}
                    material={materials.Camera_map}
                    skeleton={nodes.Object_12.skeleton}
                  />
                  
                  <group name="Object_6" />
                  <group name="Object_9" />
                  <group name="Object_11" />
                  <group name="Base">
                    <group name="Stem">
                      <group name="Camera" />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(scene)
