/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: FPSunreal (https://sketchfab.com/FPSunreal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lava-planet-9792612f76184ee3b48530c7515ce747
Title: Lava planet
*/

import React, { useEffect, useRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"
import scene from "../assets/3d/lava_planet.glb"
import { useFrame } from "@react-three/fiber"

export function Planet(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)
  const groupRef = useRef()


    
  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.0001 
    }
  })

  return (
    <group ref={groupRef} {...props} dispose={null} scale={[10, 10, 10]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-1.288, 0.397, 1.392]}>
          <group
            name="487bdfa2f7f248b4be2e165de1109409fbx"
            rotation={[Math.PI / 2, 10, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="planet"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="planet_planet_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.planet_planet_0.geometry}
                    material={materials.planet}
                  />
                </group>
                <group
                  name="clouds"
                  rotation={[-Math.PI / 2, 0, 1.91]}
                  scale={100}
                >
                  <mesh
                    name="clouds_clouds_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.clouds_clouds_0.geometry}
                    material={materials.clouds}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(scene)
