/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Marcel Schanz (https://sketchfab.com/mschanz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/surveillance-cam-3d7f98993ee340179af212e465dd8b4e
Title: Surveillance Cam
*/

import { useEffect, useRef, useState } from "react"
import { useGLTF } from "@react-three/drei"
import scene from "../assets/3d/surveillance_cam.glb"
import { MathUtils } from "three"

export function SurveillanceCam(props) {
  const group = useRef()
  const [mousePos, setMousePos] = useState({ x: 0, y: 0 })
  const { nodes, materials } = useGLTF(scene)

  const handleMouseMove = (event) => {
    setMousePos({
      x: (event.clientX / window.innerWidth) * 2 - 1,
      y: -(event.clientY / window.innerHeight) * 2 + 1,
    })
  }

  useEffect(() => {
    window.addEventListener("mousemove", handleMouseMove)
    return () => {
      window.removeEventListener("mousemove", handleMouseMove)
    }
  }, [])

  useEffect(() => {
    if (group.current) {
      group.current.rotation.y = MathUtils.lerp(
        group.current.rotation.y,
        (mousePos.x * Math.PI) / 5,
        0.1
      )

      group.current.rotation.x = MathUtils.lerp(
        group.current.rotation.x,
        -(mousePos.y * Math.PI) / 20,
        0.1
      )
    }
  }, [mousePos])

  return (
    <group ref={group} {...props} dispose={null} position={[0, 1.5, -10]}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 3.5]}
          scale={0.028}
        >
          <group
            name="223ae2cdea7846c7846301369b16eb04fbx"
            rotation={[1.6, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials.standard_varnish}
                    skeleton={nodes.Object_10.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(scene)
