/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Marcel Schanz (https://sketchfab.com/mschanz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/surveillance-cam-3d7f98993ee340179af212e465dd8b4e
Title: Surveillance Cam
*/

import React, { useRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"
import scene from "../assets/3d/surveillance_cam2.glb"

export function SurveillanceCamFoot(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} position={[0, 1.5, -10]}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 4.2]}
          scale={0.025}
        >
          <group
            name="223ae2cdea7846c7846301369b16eb04fbx"
            rotation={[Math.PI / 2, -0.1, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_12"
                    geometry={nodes.Object_12.geometry}
                    material={materials.standard_varnish}
                    skeleton={nodes.Object_12.skeleton}
                  />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.standard_varnish}
                    skeleton={nodes.Object_7.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(scene)
